apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: texting-ingress
spec:
  rules:
  - host: texting.local
    http:
      paths:
      - path: /
        backend:
          service:
            name: secure-texting
            port:
              number: 80
        pathType: Prefix
